require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - bin/*

#
# Linters
#

#
# Naming
#

#
# Layout
#
Layout/LineLength:
  Max: 120
  Exclude:
    - config/initializers/devise.rb

#
# Metrics
#

#
# Style
#
Style/Documentation:
  Enabled: false

#
# RSpec
#
