require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - bin/*
    - vendor/**/*

#
# Linters
#

#
# Naming
#

#
# Layout
#

#
# Metrics
#

#
# Style
#
Style/Documentation:
  Enabled: false

#
# RSpec
#
