name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    # Prepare
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    # Tests
    - name: Lint
      run: bundle exec rubocop -DSE --force-exclusion -c .rubocop.yml

    - name: Update audit
      run: bundle audit update

    - name: Audit
      run: bundle audit check
